// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE0pHdCs-JH00KVlW0PuBnvTPbEq2cMSA',
    appId: '1:202527068217:web:f625f5a684c0e762697de8',
    messagingSenderId: '202527068217',
    projectId: 'ecommerceapp-10ccc',
    authDomain: 'ecommerceapp-10ccc.firebaseapp.com',
    storageBucket: 'ecommerceapp-10ccc.appspot.com',
    measurementId: 'G-6FYGXSY24N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0fjKU1YiYwxigvFhNg1MItUtn5aV65K4',
    appId: '1:202527068217:android:750feeee4498756a697de8',
    messagingSenderId: '202527068217',
    projectId: 'ecommerceapp-10ccc',
    storageBucket: 'ecommerceapp-10ccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2EFmHcmMg4XlkpdLGEaPK24dlERcG0c',
    appId: '1:202527068217:ios:f3295c8224b9840a697de8',
    messagingSenderId: '202527068217',
    projectId: 'ecommerceapp-10ccc',
    storageBucket: 'ecommerceapp-10ccc.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT2EFmHcmMg4XlkpdLGEaPK24dlERcG0c',
    appId: '1:202527068217:ios:f3295c8224b9840a697de8',
    messagingSenderId: '202527068217',
    projectId: 'ecommerceapp-10ccc',
    storageBucket: 'ecommerceapp-10ccc.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
